# Generated by Django 3.2.3 on 2021-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_inward_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
