# Generated by Django 3.2.3 on 2021-05-25 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_inward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='quantity',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveBigIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inward')),
            ],
        ),
    ]
