# Generated by Django 3.2.3 on 2021-05-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210525_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'verbose_name_plural': 'Dispatch'},
        ),
        migrations.AlterModelOptions(
            name='inward',
            options={'verbose_name_plural': 'Inward'},
        ),
    ]
