# Generated by Django 3.2.3 on 2021-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_book_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bulk', 'Bulk'), ('Pallet', 'Pallet')], max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chamber',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
