# Generated by Django 3.2.3 on 2021-06-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210615_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='inward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inward'),
        ),
    ]
