# Generated by Django 3.2.3 on 2021-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_chamber_inward'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='date',
            field=models.DateTimeField(default=True),
        ),
    ]
