# Generated by Django 3.2.3 on 2021-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_inward_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
