# Generated by Django 3.2.3 on 2021-06-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_inward_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
