# Generated by Django 3.2.3 on 2021-06-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_inward_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='date',
        ),
    ]
