# Generated by Django 3.2.3 on 2021-06-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_inward_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='date',
        ),
    ]
